// Step 2: Power Query replacement for Global_Inflow_Outflow.
//
// Paste this into the Advanced Editor of the Global_Inflow_Outflow query
// after bi_reporting.io_2_asp_mv has been created.

let
    Source = PostgreSQL.Database("SERVER_NAME", "DATABASE_NAME"),
    Step2Asp = Value.NativeQuery(
        Source,
        "
        select
            ""Source Side"",
            ""Sell-in Region"",
            ""Sell-in Sub"",
            ""Sell-in AP1"",
            ""Sell-in Account"",
            ""Sell-out Region"",
            ""Sell-out Sub"",
            ""Sell-out Country"",
            ""Current Region"",
            ""Current Sub"",
            ""Current Country"",
            ""Biz Sub"",
            ""Series"",
            ""MKT Name"",
            ""Memory"",
            ""Storage"",
            ""Item Code"",
            ""Month"",
            ""Year"",
            ""ItemID"",
            ""Grand total"",
            ""ASP"",
            ""Biz Grp"",
            ""Sell-in Channel"",
            ""Sell-in Country"",
            ""SKU"",
            ""In/Out"",
            ""Region"",
            ""Subsidiary"",
            ""Across Sub"",
            ""Active Qty"",
            ""Total Inflow"",
            ""From MENA"",
            ""From Non-MENA"",
            ""Total Outflow"",
            ""To MENA Outflow"",
            ""To Non-MENA"",
            ""S/O SCM"",
            ""Domestic Demand"",
            ""S/O that Stays"",
            ""2nd Activation In"",
            ""2nd Activation Out"",
            ""CI In"",
            ""CI Out"",
            ""Parallel S/O""
        from bi_reporting.io_2_asp_mv
        ",
        null,
        [EnableFolding = true]
    ),
    #"Changed Type" = Table.TransformColumnTypes(
        Step2Asp,
        {
            {"Source Side", type text},
            {"Sell-in Region", type text},
            {"Sell-in Sub", type text},
            {"Sell-in AP1", type text},
            {"Sell-in Account", type text},
            {"Sell-out Region", type text},
            {"Sell-out Sub", type text},
            {"Sell-out Country", type text},
            {"Current Region", type text},
            {"Current Sub", type text},
            {"Current Country", type text},
            {"Biz Sub", type text},
            {"Series", type text},
            {"MKT Name", type text},
            {"Memory", type text},
            {"Storage", type text},
            {"Item Code", type text},
            {"Month", Int64.Type},
            {"Year", type text},
            {"ItemID", type text},
            {"Grand total", type text},
            {"ASP", type number},
            {"Biz Grp", type text},
            {"Sell-in Channel", type text},
            {"Sell-in Country", type text},
            {"SKU", type text},
            {"In/Out", type text},
            {"Region", type text},
            {"Subsidiary", type text},
            {"Across Sub", type text},
            {"Active Qty", type number},
            {"Total Inflow", type number},
            {"From MENA", type number},
            {"From Non-MENA", type number},
            {"Total Outflow", type number},
            {"To MENA Outflow", type number},
            {"To Non-MENA", type number},
            {"S/O SCM", type number},
            {"Domestic Demand", type number},
            {"S/O that Stays", type number},
            {"2nd Activation In", type number},
            {"2nd Activation Out", type number},
            {"CI In", type number},
            {"CI Out", type number},
            {"Parallel S/O", type number}
        }
    )
in
    #"Changed Type"
